<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <RootNamespace>ParalivesMultiplayer.ConsoleClient</RootNamespace>
    <AssemblyName>ConsoleClient</AssemblyName>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ParalivesMultiplayer.Protocol\ParalivesMultiplayer.Protocol.csproj" />
  </ItemGroup>

</Project>